### ISSUE TITLE
freezing at first revision with content

### ISSUE THREAD

**Issue by tiramon** [svn-all-fast-export/svn2git#84]
I have to migrate an old svn repository to git.
I tried if my rules are working with --dry-run until all looked good, but when i'm starting the tool without the dry-run parameter it freezes at the first revision with content 

>Exporting revision 7487  nothing to do
>Exporting revision 7488  nothing to do
>Exporting revision 7489 .

At that spot it's frozen for hours without any relevant cpu or memory usage
After a while i tried to start it with --debug-rules and could see that it founds a match for first file in the first revision with content and then does nothing for ... some time

>Exporting revision 7487  nothing to do
>Exporting revision 7488  nothing to do
>Exporting revision 7489 rev 7489 /TMS/trunk/tms/.classpath matched rule: "../svn2git.rules:4 /TMS/trunk/"    exporting.
>.add/change file ( /TMS/trunk/tms/.classpath -> "master" "tms/.classpath"`

- I installed cygwin and am running it on a win10 pc
- I made a local copy of our svn repository with 'svnrdump dump' and 'svnadmin load'

I call  
>~/svn2git/svn-all-fast-export.exe --debug-rules --identity-map ../trunk/authors-transform.txt --rules ../svn2git.rules local

and my current rules are pretty simple 
```
create repository tms
end repository

match /TMS/trunk/
	repository tms
	branch master
end match

match /TMS/branches/Feature_Branches/([^/]+)/
	repository tms
	branch feature/\1
end match

match /TMS/branches/([^/]+)/
	repository tms
	branch \1
end match

match /TMS/tags/([^/]+)/
	repository tms
	branch ref/tags/\1
	annotated true
end match
```

**Comment by eeijlar** [comment]
When it gets to the point where it's stuck, do a 'pstack <pid of svn2git>', and it will show you were it's getting stuck. If it's in an infinite loop, you will have to skip that branch, as follows:

```
match /path/to/dud/branch/
end match
```

There can be several different issues when converting from SVN. These include invalid branch names, incorrect use of the svn copy command and creating circular dependencies in the SVN history.

**_Invalid branch names / circular dependencies_**

A common occurance is where someone creates a branch in `MyProject/branches` for example. Let's say it is called `my_branch`. They then copy `MyProject/branches` into their branch. This causes an infinite loop where the conversion tool tries to process the branch, finds `MyProject/branches` in there, then finds the branch again, and continues forever. You can identify this scenario as follows:

If the process gets stuck processing a node (5 minutes or more printing '+' to the screen), do `pstack <pid of svn2git>`, and locate the branch it's stuck on. Add that to the ruleset and restart the conversion.

**_Core dumps_**

Instead of getting stuck, the tool may also core dump. You can examine the core as follows:

gdb /path/to/svn2git core.NNNN

It may tell you to install debug libraries which you can do first. The core may provide useful information as to where the tool was when it core dumped. svn2git tends to core rather than writing message to the console about what went wrong.

**_Log files_**

svn2git generates a log file for each repository it tries to convert. These can contain information about what went wrong with the conversion.
General gotchas

Don't try and convert too many things at once or you may cause the machine to run out of resources. This will result in random cores with not much useful information in them.

**Comment by tiramon** [comment]
No idea what exactly the problem was running it with cygwin on windows.
My solution was to download a ubuntu vm, copy all relevant files and run it there and it seams that it is working without a problem
